on:
  push:
  schedule:
  - cron: '40 * * * *'

jobs:
  cron:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch latest JSON
      run: |
        for FILENAME in ips-v4 ips-v6; do
        	curl --silent --show-error "https://www.cloudflare.com/${FILENAME}" | ./sort.py >"${FILENAME}"
        done
    - name: Commit if dirty
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        if [ -n "$(git status --porcelain)" ]; then
        	pip3 install -r requirements.txt
        	git diff | egrep '^[-+][^-+]' | TO=cloudflare-ips@googlegroups.com SUBJECT='update notice' ./gmail.py
        	git config --global user.name 'GitHub Actions'
        	git config --global user.email "$(whoami)@$(hostname --fqdn)"
        	git add --all
        	git commit --all --message 'IP ranges updated'
        	git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master
        fi
